image: python:3.9

stages:
  - format
  - security

before_script:
  - python3 setup.py install

flake8:
  stage: format
  script:
    - flake8 . --config .flake8

isort:
  stage: format
  script:
    - python3 -m isort --check --diff genbase

bandit:
  stage: security
  script:
    - bandit -r ./genbase -x /test
